---
title: Diagnostic Plots in R
author: Jes LaCourse
date: '2022-11-26'
slug: []
categories: []
tags: []
description: ''
draft: yes
---

# Recap

Here are our 20 subjects: 


```{r setup, include = F}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
library(plotly)
library(kableExtra)

theme_set(theme_bw())
```

```{r createSample, echo= F}
# Fix our sample 
set.seed(1002)

# x : I want 20 subjects between 18 and 60
# y : Use our known slope and intercept to set BPs.
x = sample(18:60, 20, replace = T)
y = round(rnorm(20, mean = x*0.9, sd = 15) + 90, 0)  

data <- data.frame(Person = as.character(1:20), Age = x, BP = y)
data %>%  t %>% kable(table.attr = "style = \"color:white;\"", 
                     caption = "Blood Pressure Sample" ) %>% 
               kable_paper()

lm(formula = BP~Age, data) -> m

```

# Diagnostics

Built in diagnostic plots

```{r plotResidShowCode, eval=FALSE}
data %>%
  {
  ggplot(.,aes(x = Age, y = BP)) + 
  geom_smooth(method = "lm", color = "gray", fill = "light gray") + # Linear estimate
  geom_point(aes(y = Predicted),                                    # Predicted values
             shape = 1, size = 3.5) +
  geom_segment(aes(xend = Age, yend = Predicted), alpha = 0.5) +    
  geom_point(size = 2, color = "black") +                           # Actual values
  geom_text(aes(label = Person), hjust  = 1.6, size = 3)
  }

```




```{r}
par(mfrow = c(2,2))
plot(m)

data %>% 
  ggplot() + 
  geom_histogram(aes(x = Residuals), bins = 10, color = "black") 

```